# Netlify "kitchen sink" example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml

# NOTE: Config from `config.js` is merged in here.

localhost_development:
  backend:
    name: file-system
    api_root: /api

backend:
  name: github
  repo: artsy/palette
  branch: master
  # squash_merges: true

display_url: palette.artsy.net
media_folder: static/assets
public_folder: assets
